function Set-McpServerUrls {
    <#
    .SYNOPSIS
        Injects MCP server URLs into plugin JSON files and generates a .env.install file.
    .DESCRIPTION
        Reads mcp-providers.json to discover which plugin files reference each provider,
        then replaces the {{MCP_HOST}} placeholder URLs with the user-supplied URLs.
        Also generates a .env.install file at the project root for reference.
    .PARAMETER ProviderUrls
        Hashtable mapping provider names to their resolved URLs.
        Example: @{ "factset" = "https://mcp.org.com/factset"; "sec-edgar" = "https://data.sec.gov" }
    .PARAMETER ConfigPath
        Path to the mcp-providers.json configuration file.
    .PARAMETER ProjectRoot
        Root path of the CopilotFSI project.
    .PARAMETER DryRun
        If specified, logs what would change without modifying any files.
    .OUTPUTS
        System.Int32 — count of files modified.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [hashtable]$ProviderUrls,

        [Parameter(Mandatory)]
        [string]$ConfigPath,

        [Parameter(Mandatory)]
        [string]$ProjectRoot,

        [switch]$DryRun
    )

    $filesModified = 0

    # --- Load provider configuration ---
    if (-not (Test-Path $ConfigPath)) {
        Write-Error "MCP providers config not found: $ConfigPath"
        return 0
    }

    try {
        $providersConfig = Get-Content -Path $ConfigPath -Raw | ConvertFrom-Json
    }
    catch {
        Write-Error "Failed to parse MCP providers config: $_"
        return 0
    }

    # --- Process each selected provider ---
    foreach ($providerName in $ProviderUrls.Keys) {
        $newUrl = $ProviderUrls[$providerName]
        Write-Verbose "Processing provider '$providerName' → $newUrl"

        # Find provider entry in config
        $providerEntry = $providersConfig.providers | Where-Object { $_.name -eq $providerName }
        if (-not $providerEntry) {
            Write-Warning "Provider '$providerName' not found in mcp-providers.json — skipping."
            continue
        }

        $urlPattern = $providerEntry.urlPattern
        if (-not $urlPattern) {
            $urlPattern = "/mcp/$providerName"
        }

        # Build the placeholder URL that appears in source files
        $placeholderUrl = "https://{{MCP_HOST}}$urlPattern"
        Write-Verbose "  Placeholder pattern: $placeholderUrl"

        if (-not $providerEntry.pluginFiles -or $providerEntry.pluginFiles.Count -eq 0) {
            Write-Warning "No pluginFiles defined for provider '$providerName' — skipping."
            continue
        }

        foreach ($relativeFile in $providerEntry.pluginFiles) {
            $filePath = Join-Path $ProjectRoot $relativeFile

            if (-not (Test-Path $filePath)) {
                Write-Warning "Plugin file not found: $filePath — skipping."
                continue
            }

            try {
                $rawContent = Get-Content -Path $filePath -Raw

                if ($rawContent -notmatch [regex]::Escape($placeholderUrl)) {
                    Write-Verbose "  No match for placeholder in $relativeFile — skipping."
                    continue
                }

                $updatedContent = $rawContent -replace [regex]::Escape($placeholderUrl), $newUrl

                if ($DryRun) {
                    Write-Host "[DryRun] Would update '$relativeFile':"
                    Write-Host "         Old URL: $placeholderUrl"
                    Write-Host "         New URL: $newUrl"
                }
                else {
                    # Parse and re-serialize to ensure valid JSON with consistent formatting
                    try {
                        $jsonObj = $updatedContent | ConvertFrom-Json
                        $formatted = $jsonObj | ConvertTo-Json -Depth 20
                        Set-Content -Path $filePath -Value $formatted -Encoding UTF8 -NoNewline
                    }
                    catch {
                        # Fallback: write the string-replaced content directly
                        Set-Content -Path $filePath -Value $updatedContent -Encoding UTF8 -NoNewline
                    }
                    Write-Verbose "  Updated $relativeFile : $placeholderUrl → $newUrl"
                }

                $filesModified++
            }
            catch {
                Write-Error "Failed to process '$relativeFile': $_"
            }
        }
    }

    # --- Generate .env.install ---
    $envPath = Join-Path $ProjectRoot ".env.install"
    $envLines = @(
        "# FSI Copilot MCP Server Configuration"
        "# Generated by Install-FSICopilot.ps1"
    )

    foreach ($providerName in ($ProviderUrls.Keys | Sort-Object)) {
        $envKey = "MCP_" + ($providerName -replace '-', '_').ToUpper() + "_URL"
        $envLines += "$envKey=$($ProviderUrls[$providerName])"
    }

    $envContent = ($envLines -join "`n") + "`n"

    if ($DryRun) {
        Write-Host "[DryRun] Would generate $envPath :"
        Write-Host $envContent
    }
    else {
        Set-Content -Path $envPath -Value $envContent -Encoding UTF8 -NoNewline
        Write-Verbose "Generated $envPath with $($ProviderUrls.Count) provider URL(s)."
    }

    Write-Verbose "Total files modified: $filesModified"
    return $filesModified
}
